### ISSUE TITLE
Could not find com.contentgrid.opa-java-client:opa-async-java-client

### ISSUE THREAD

**Issue by henryhqhuang** [xenit-eu/thunx#70]
:thunx-gateway-spring-boot-starter:test: Could not find com.contentgrid.opa-java-client:opa-async-java-client:.
Required by:
    project :thunx-gateway-spring-boot-starter > project :thunx-pdp-opa

**Comment by tgeens** [comment]
Thanks for the report, this is fixed in #76 
I'll create a new release on of the next days.

**Comment by tgeens** [comment]
@henryhqhuang v0.6.0 was released to maven central: https://central.sonatype.com/artifact/com.contentgrid.thunx/thunx-bom/0.6.0
